# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
#TODO finish this
modId="yacm"
version="${file.jarVersion}"
displayName="YACM"
credits="notPlancha"
authors="notPlancha"
description='''
Yet Another Currency Mod
'''
updateJSONURL= "" #TODO
[[dependencies.yacm]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yacm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)" #tested only on 1.18.2
    ordering="NONE"
    side="BOTH"
